# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  body_listener: true
  param_fetcher_listener: true
  routing_loader: true
  view:
    view_response_listener: 'force'
  format_listener:
    rules:
      - {path: '^/', stop: true, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
